{% set python_min = "3.9" %}
{% set name = "poligrain" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/poligrain-{{ version }}.tar.gz
  sha256: 67b5948c122300636368b5d5b192ef2368093cea2020923fe489c13aa1662bf1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - poetry-dynamic-versioning
    - pip
  run:
    - python >={{ python_min }},<4.0.0
    - netcdf4 >=1.6.5
    - xarray >=2023.12.0
    - matplotlib-base >=3.8.2
    - pyproj >=3.6.1
    - scipy >=1.12.0
    - sparse
    - shapely

test:
  imports:
    - poligrain
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/OpenSenseAction/poligrain
  summary: Effortlessly plot and compare (rainfall) sensor data with point, line and grid geometry.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cchwala
