{% set name = "poligrain" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/poligrain-{{ version }}.tar.gz
  sha256: 4b84bac1b5c2658a5cee379bc9146b155bea1324e91f040521e027b032ed07c9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - poetry-core >=1.0.0
    - poetry-dynamic-versioning
    - pip
  run:
    - python >=3.10, <4.0.0
    - netcdf4 >=1.6.5
    - xarray >=2023.12.0
    - matplotlib-base >=3.8.2
    - pyproj >=3.6.1
    - scipy >=1.12.0
    - sparse
    - shapely

test:
  imports:
    - poligrain
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/OpenSenseAction/poligrain
  summary: Effortlessly plot and compare (rainfall) sensor data with point, line and grid geometry.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cchwala
